apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongodb-poc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    # These labels are required by helm. You can read more about required labels in the chart best pracices guide:
    # https://docs.helm.sh/chart_best_practices/#standard-labels
    helm.sh/chart: {{ include "mongodb-poc.chart" . }}
    app.kubernetes.io/name: {{ include "mongodb-poc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mongodb-poc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mongodb-poc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          {{- toYaml .Values.env | nindent 10 }}

        ports:
          - name: {{ .Values.container.name }}
            containerPort: {{ .Values.container.port }}
            protocol: TCP

        {{- if .Values.health.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.health.checkUrl }}
            port: {{ .Values.container.port }}
          initialDelaySeconds: {{ .Values.health.livenessInitialDelay | default 120 }}
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: {{ .Values.health.checkUrl }}
            port: {{ .Values.container.port }}
          initialDelaySeconds: {{ .Values.health.readinessInitialDelay | default 10 }}
          timeoutSeconds: 10
        {{- end }}

        resources:
          {{- toYaml .Values.resources | nindent 10 }}
