apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongodb-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    # These labels are required by helm. You can read more about required labels in the chart best pracices guide:
    # https://docs.helm.sh/chart_best_practices/#standard-labels
    helm.sh/chart: {{ include "mongodb-chart.chart" . }}
    app.kubernetes.io/name: {{ include "mongodb-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mongodb-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mongodb-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: mongodb-server
        image: mongo:4
        ports:
          - containerPort: 27017
