apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    # These labels are required by helm. You can read more about required labels in the chart best pracices guide:
    # https://docs.helm.sh/chart_best_practices/#standard-labels
    helm.sh/chart: {{ include "mongodb-chart.chart" . }}
    app.kubernetes.io/name: {{ include "mongodb-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "mongodb-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
