apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    app: {{ .Values.appName | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName | quote }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            cpu: {{ .Values.resources.cpuBase | quote }}
            memory: {{ .Values.resources.memory | quote }}
          limits:
            cpu: {{ .Values.resources.cpuMax | quote }}
            memory: {{ .Values.resources.memory | quote }}
        ports:
          - containerPort: {{ .Values.containerPort }}

        # Configuration and secrets
        env:
          {{- range .Values.environmentVars }}
          - name: {{ .name }}
            value: {{ .value }}
          {{- end }}
          {{- range .Values.secrets }}
          - name: {{ .name }}
            valueFrom:
              secretKeyRef:
                name: {{ .secretRef }}
                key: {{ .fieldName }}
          {{- end }}
        {{- if gt (len .Values.mountedSecrets.secrets) 0 }}
        volumeMounts:
          {{- range .Values.mountedSecrets.secrets }}
          - name: {{ .name }}
            mountPath: {{ $.Values.mountedSecrets.mountPath }}
            readOnly: true
          {{- end }}
        {{- end }}
        # Health checks
        readinessProbe:
          httpGet:
            path: {{ .Values.healthCheck.path | quote }}
            port: {{ .Values.healthCheck.port }}
          initialDelaySeconds: {{ .Values.healthCheck.readinessDelaySeconds }}
          periodSeconds: {{ .Values.healthCheck.periodSeconds }}
        livenessProbe:
          httpGet:
            path: {{ .Values.healthCheck.path | quote }}
            port: {{ .Values.healthCheck.port }}
          initialDelaySeconds: {{ .Values.healthCheck.livenessDelaySeconds }}
          periodSeconds: {{ .Values.healthCheck.periodSeconds }}

      {{- if gt (len .Values.mountedSecrets.secrets) 0 }}
      volumes:
        {{- range .Values.mountedSecrets.secrets }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretRef }}
            items:
              - key: {{ .fieldName }}
                path: {{ .path }}
        {{- end }}
      {{- end }}
